package offerfinderalpha;
// Generated 12 Íןו 2014 8:19:55 לל by Hibernate Tools 4.3.1



/**
 * Stores generated by hbm2java
 */
public class Stores  implements java.io.Serializable {


     private Integer id;
     private String name;

    public Stores() {
    }

    public Stores(String name) {
       this.name = name;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


